# Generated by Django 5.2 on 2025-04-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folha', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3')], default='A4', max_length=2, verbose_name='Tipo de folha')),
                ('colorida', models.BooleanField(default=False)),
                ('quantidade', models.IntegerField()),
                ('preco_unidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unidade')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(upload_to='maquinas')),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.CharField(max_length=100)),
                ('tipo_aquisicao', models.CharField(choices=[('A', 'Alugada'), ('V', 'Vendida'), ('E', 'Externa')], default='A', max_length=1)),
                ('frequencia_manutencao', models.IntegerField(help_text='Frequência da manutenção em meses', verbose_name='Frequência de manutenção em meses')),
                ('franquia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_clientes', to='maquinas.franquia')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinas_instanciadas', to='maquinas.maquina')),
            ],
        ),
    ]
