# Generated by Django 5.2 on 2025-04-25 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=112, null=True)),
                ('telefone', models.CharField(blank=True, max_length=25, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True, verbose_name='C.P.F.')),
                ('cpf', models.CharField(blank=True, max_length=25, null=True, verbose_name='C.N.P.J')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enderecos.endereco', verbose_name='Endereço')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=112, null=True)),
                ('telefone', models.CharField(blank=True, max_length=25, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True, verbose_name='C.P.F.')),
                ('cpf', models.CharField(blank=True, max_length=25, null=True, verbose_name='C.N.P.J')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('setor', models.CharField(choices=[('A', 'Administrativo'), ('T', 'Técico'), ('C', 'Comercial')], default='A', max_length=1)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enderecos.endereco', verbose_name='Endereço')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
