# Generated by Django 5.2 on 2025-05-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_remove_endereco_cliente_remove_endereco_funcionario'),
        ('usuarios', '0002_remove_funcionario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enderecos.endereco'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enderecos.endereco'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='setor',
            field=models.CharField(choices=[('A', 'Administrativo'), ('T', 'Técnico'), ('C', 'Comercial')], default='A', max_length=1),
        ),
    ]
