# Generated by Django 5.2 on 2025-05-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_endereco_cliente_endereco_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='funcionario',
        ),
    ]
