# Generated by Django 5.2 on 2025-05-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copiadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('cartucho', models.CharField(max_length=100)),
                ('caracteristicas', models.TextField()),
                ('velocidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveIntegerField(help_text='Período da franquia em meses')),
                ('folha', models.CharField(help_text='Tipo de folha (ex: A4, Ofício, etc.)', max_length=100)),
                ('colorida', models.BooleanField(default=False, help_text='Marque se a impressão é colorida')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CopiadoraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.CharField(max_length=100, unique=True)),
                ('tipo_aquisicao', models.CharField(choices=[('alugada', 'Alugada'), ('vendida', 'Vendida'), ('externo', 'Externo')], max_length=10)),
                ('frequencia_manutencao', models.PositiveIntegerField(blank=True, help_text='Frequência da manutenção em meses', null=True)),
                ('copiadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copiadoras.copiadora')),
                ('franquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copiadoras.franquia')),
            ],
        ),
        migrations.AddField(
            model_name='copiadora',
            name='funcionalidades',
            field=models.ManyToManyField(blank=True, to='copiadoras.funcionalidade'),
        ),
        migrations.CreateModel(
            name='ImagemCopiadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='copiadoras/')),
                ('copiadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='copiadoras.copiadora')),
            ],
        ),
    ]
